<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Categories.php');
	include_once(__DIR__ . '/Categories_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Categories');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Categories';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Categories`.`id`" => "id",
		"`Categories`.`Category_name`" => "Category_name",
		"`Categories`.`Description`" => "Description",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Categories`.`id`',
		2 => 2,
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Categories`.`id`" => "id",
		"`Categories`.`Category_name`" => "Category_name",
		"`Categories`.`Description`" => "Description",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Categories`.`id`" => "ID",
		"`Categories`.`Category_name`" => "Category",
		"`Categories`.`Description`" => "Description",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Categories`.`id`" => "id",
		"`Categories`.`Category_name`" => "Category_name",
		"`Categories`.`Description`" => "Description",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Categories` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Categories_view.php';
	$x->TableTitle = 'Categories';
	$x->TableIcon = 'resources/table_icons/barchart.png';
	$x->PrimaryKey = '`Categories`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Category', 'Description', ];
	$x->ColFieldName = ['Category_name', 'Description', ];
	$x->ColNumber  = [2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Categories_templateTV.html';
	$x->SelectedTemplate = 'templates/Categories_templateTVS.html';
	$x->TemplateDV = 'templates/Categories_templateDV.html';
	$x->TemplateDVP = 'templates/Categories_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Categories_init
	$render = true;
	if(function_exists('Categories_init')) {
		$args = [];
		$render = Categories_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Categories_header
	$headerCode = '';
	if(function_exists('Categories_header')) {
		$args = [];
		$headerCode = Categories_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Categories_footer
	$footerCode = '';
	if(function_exists('Categories_footer')) {
		$args = [];
		$footerCode = Categories_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
