<?php

// Data functions (insert, update, delete, form) for table Projects

// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

function Projects_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Projects');
	if(!$arrPerm['insert']) return false;

	$data = [
		'Projects_name' => Request::val('Projects_name', ''),
		'Description' => Request::val('Description', ''),
		'Category' => Request::lookup('Category', ''),
		'ProjectTags' => Request::multipleChoice('ProjectTags', ''),
		'Image_1' => Request::fileUpload('Image_1', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Projects', 'Image_1', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Projects', 'Image_1', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Projects', 'Image_1', Request::val('SelectedID'));
			},
		]),
		'Image_Uploaded' => Request::fileUpload('Image_Uploaded', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('Projects', 'Image_Uploaded', Request::val('SelectedID'));
			},
		]),
		'Geo_place' => Request::val('Geo_place', ''),
	];


	// hook: Projects_before_insert
	if(function_exists('Projects_before_insert')) {
		$args = [];
		if(!Projects_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Projects', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Projects', $recID, calculated_fields()['Projects']);

	// hook: Projects_after_insert
	if(function_exists('Projects_after_insert')) {
		$res = sql("SELECT * FROM `Projects` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Projects_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Projects', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Projects_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Projects_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Projects_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Projects', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Projects_before_delete
	if(function_exists('Projects_before_delete')) {
		$args = [];
		if(!Projects_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// delete file stored in the 'Image_1' field
	$res = sql("SELECT `Image_1` FROM `Projects` WHERE `id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
			$thumbDV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_dv.$1', $row[0]);
			$thumbTV = preg_replace('/\.(jpg|jpeg|gif|png|webp)$/i', '_tv.$1', $row[0]);
			@unlink(getUploadDir('') . $thumbTV);
			@unlink(getUploadDir('') . $thumbDV);
		}
	}

	// delete file stored in the 'Image_Uploaded' field
	$res = sql("SELECT `Image_Uploaded` FROM `Projects` WHERE `id`='{$selected_id}'", $eo);
	if($row = @db_fetch_row($res)) {
		if($row[0] != '') {
			@unlink(getUploadDir('') . $row[0]);
		}
	}

	sql("DELETE FROM `Projects` WHERE `id`='{$selected_id}'", $eo);

	// hook: Projects_after_delete
	if(function_exists('Projects_after_delete')) {
		$args = [];
		Projects_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Projects' AND `pkValue`='{$selected_id}'", $eo);
}

function Projects_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Projects', $selected_id, 'edit')) return false;

	$data = [
		'Projects_name' => Request::val('Projects_name', ''),
		'Description' => Request::val('Description', ''),
		'Category' => Request::lookup('Category', ''),
		'ProjectTags' => Request::multipleChoice('ProjectTags', ''),
		'Image_1' => Request::fileUpload('Image_1', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				createThumbnail($name, getThumbnailSpecs('Projects', 'Image_1', 'tv'));
				createThumbnail($name, getThumbnailSpecs('Projects', 'Image_1', 'dv'));
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('Projects', 'Image_1', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);

				// delete thumbnails
				preg_match('/^[a-z0-9_]+\.(jpg|jpeg|gif|png|webp)$/i', $oldFile, $m);
				$thumbDV = str_replace(".{$m[1]}ffffgggg", "_dv.{$m[1]}", $oldFile . 'ffffgggg');
				$thumbTV = str_replace(".{$m[1]}ffffgggg", "_tv.{$m[1]}", $oldFile . 'ffffgggg');
				@unlink(getUploadDir('') . $thumbTV);
				@unlink(getUploadDir('') . $thumbDV);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Projects', 'Image_1', $selected_id);
			},
		]),
		'Image_Uploaded' => Request::fileUpload('Image_Uploaded', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
			},
			'removeOnSuccess' => true,
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// delete old file from server
				$oldFile = existing_value('Projects', 'Image_Uploaded', $selected_id);
				if(!$oldFile) return;

				@unlink(getUploadDir('') . $oldFile);
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('Projects', 'Image_Uploaded', $selected_id);
			},
		]),
		'Geo_place' => Request::val('Geo_place', ''),
	];

	// get existing values
	$old_data = getRecord('Projects', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Projects_before_update
	if(function_exists('Projects_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Projects_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Projects', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Projects_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Projects', $data['selectedID'], calculated_fields()['Projects']);

	// hook: Projects_after_update
	if(function_exists('Projects_after_update')) {
		$res = sql("SELECT * FROM `Projects` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!Projects_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Projects' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Projects_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Projects');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_Category = Request::val('filterer_Category');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Category
	$combo_Category = new DataCombo;
	// combobox: ProjectTags
	$combo_ProjectTags = new Combo;
	$combo_ProjectTags->ListType = 3;
	$combo_ProjectTags->MultipleSeparator = ', ';
	$combo_ProjectTags->ListBoxHeight = 10;
	$combo_ProjectTags->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Projects.ProjectTags.csv')) {
		$ProjectTags_data = addslashes(implode('', @file(__DIR__ . '/hooks/Projects.ProjectTags.csv')));
		$combo_ProjectTags->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($ProjectTags_data))));
		$combo_ProjectTags->ListData = $combo_ProjectTags->ListItem;
	} else {
		$combo_ProjectTags->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("bob;;ret;kjg;;dsad"))));
		$combo_ProjectTags->ListData = $combo_ProjectTags->ListItem;
	}
	$combo_ProjectTags->SelectName = 'ProjectTags';

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='Projects' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='Projects' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `Projects` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Projects_view.php', false);
		}
		$combo_Category->SelectedData = $row['Category'];
		$combo_ProjectTags->SelectedData = $row['ProjectTags'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_Category->SelectedData = $filterer_Category;
	}
	$combo_Category->HTML = '<span id="Category-container' . $rnd1 . '"></span><input type="hidden" name="Category" id="Category' . $rnd1 . '" value="' . html_attr($combo_Category->SelectedData) . '">';
	$combo_Category->MatchText = '<span id="Category-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Category" id="Category' . $rnd1 . '" value="' . html_attr($combo_Category->SelectedData) . '">';
	$combo_ProjectTags->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Category__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Category'] : htmlspecialchars($filterer_Category, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(Category_reload__RAND__) == 'function') Category_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Category_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#Category-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Category__RAND__.value, t: 'Projects', f: 'Category' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Category"]').val(resp.results[0].id);
							$j('[id=Category-container-readonly__RAND__]').html('<span class="match-text" id="Category-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categories_view_parent]').hide(); } else { $j('.btn[id=Categories_view_parent]').show(); }


							if(typeof(Category_update_autofills__RAND__) == 'function') Category_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Projects', f: 'Category' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_Category__RAND__.value = e.added.id;
				AppGini.current_Category__RAND__.text = e.added.text;
				$j('[name="Category"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categories_view_parent]').hide(); } else { $j('.btn[id=Categories_view_parent]').show(); }


				if(typeof(Category_update_autofills__RAND__) == 'function') Category_update_autofills__RAND__();
			});

			if(!$j("#Category-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Category__RAND__.value, t: 'Projects', f: 'Category' },
					success: function(resp) {
						$j('[name="Category"]').val(resp.results[0].id);
						$j('[id=Category-container-readonly__RAND__]').html('<span class="match-text" id="Category-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categories_view_parent]').hide(); } else { $j('.btn[id=Categories_view_parent]').show(); }

						if(typeof(Category_update_autofills__RAND__) == 'function') Category_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Category__RAND__.value, t: 'Projects', f: 'Category' },
				success: function(resp) {
					$j('[id=Category-container__RAND__], [id=Category-container-readonly__RAND__]').html('<span class="match-text" id="Category-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Categories_view_parent]').hide(); } else { $j('.btn[id=Categories_view_parent]').show(); }

					if(typeof(Category_update_autofills__RAND__) == 'function') Category_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Projects_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Projects_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Title details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Projects_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Projects_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Projects_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm['delete'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['delete'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['delete'] == 3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#Projects_name').replaceWith('<div class=\"form-control-static\" id=\"Projects_name\">' + (jQuery('#Projects_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Category').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Category_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#ProjectTags').replaceWith('<div class=\"form-control-static\" id=\"ProjectTags\">' + (jQuery('#ProjectTags').val() || '') + '</div>'); jQuery('#ProjectTags-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#s2id_ProjectTags').remove();\n";
		$jsReadOnly .= "\tjQuery('#Image_1').replaceWith('<div class=\"form-control-static\" id=\"Image_1\">' + (jQuery('#Image_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Image_Uploaded').replaceWith('<div class=\"form-control-static\" id=\"Image_Uploaded\">' + (jQuery('#Image_Uploaded').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Image_Uploaded, #Image_Uploaded-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('#Geo_place').replaceWith('<div class=\"form-control-static\" id=\"Geo_place\">' + (jQuery('#Geo_place').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Geo_place, #Geo_place-edit-link').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Category)%%>', $combo_Category->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Category)%%>', $combo_Category->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Category)%%>', urlencode($combo_Category->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(ProjectTags)%%>', $combo_ProjectTags->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(ProjectTags)%%>', $combo_ProjectTags->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['Category' => ['Categories', 'Category'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Projects_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Category)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ProjectTags)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Image_1)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="Image_1" id="Image_1" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	if($AllowUpdate && $row['Image_1'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(Image_1)%%>', '<br><input type="checkbox" name="Image_1_remove" id="Image_1_remove" value="1"> <label for="Image_1_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(Image_1)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(Image_Uploaded)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<i class="glyphicon glyphicon-remove text-danger clear-upload hidden"></i> <input type="file" name="Image_Uploaded" id="Image_Uploaded" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" accept=".jpg,.jpeg,.gif,.png,.webp">'), $templateCode);
	if($AllowUpdate && $row['Image_Uploaded'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(Image_Uploaded)%%>', '<br><input type="checkbox" name="Image_Uploaded_remove" id="Image_Uploaded_remove" value="1"> <label for="Image_Uploaded_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(Image_Uploaded)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(Geo_place)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Projects_name)%%>', safe_html($urow['Projects_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Projects_name)%%>', html_attr($row['Projects_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Projects_name)%%>', urlencode($urow['Projects_name']), $templateCode);
		if($AllowUpdate || $AllowInsert) {
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5">' . safe_html(htmlspecialchars_decode($row['Description'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<div id="Description" class="form-control-static">' . $row['Description'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(Description)%%>', nl2br($row['Description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode($urow['Description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Category)%%>', safe_html($urow['Category']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Category)%%>', html_attr($row['Category']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Category)%%>', urlencode($urow['Category']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ProjectTags)%%>', safe_html($urow['ProjectTags']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ProjectTags)%%>', html_attr($row['ProjectTags']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ProjectTags)%%>', urlencode($urow['ProjectTags']), $templateCode);
		$row['Image_1'] = ($row['Image_1'] != '' ? $row['Image_1'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Image_1)%%>', safe_html($urow['Image_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Image_1)%%>', html_attr($row['Image_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Image_1)%%>', urlencode($urow['Image_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Image_Uploaded)%%>', safe_html($urow['Image_Uploaded']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Image_Uploaded)%%>', html_attr($row['Image_Uploaded']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Image_Uploaded)%%>', urlencode($urow['Image_Uploaded']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Geo_place)%%>', safe_html($urow['Geo_place']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Geo_place)%%>', html_attr($row['Geo_place']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Geo_place)%%>', urlencode($urow['Geo_place']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Projects_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Projects_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(Description)%%>', '<textarea name="Description" id="Description" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(Category)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Category)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ProjectTags)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ProjectTags)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Image_1)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(Image_Uploaded)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Image_Uploaded)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Geo_place)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Geo_place)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
			$templateCode.="\n\tif(document.getElementById('Image_UploadedEdit')) { document.getElementById('Image_UploadedEdit').style.display='inline'; }";
			$templateCode.="\n\tif(document.getElementById('Image_UploadedEditLink')) { document.getElementById('Image_UploadedEditLink').style.display='none'; }";
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Projects');
	if($selected_id) {
		$jdata = get_joined_record('Projects', $selected_id);
		if($jdata === false) $jdata = get_defaults('Projects');
		$rdata = $row;
	}
	$templateCode .= loadView('Projects-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Projects_dv
	if(function_exists('Projects_dv')) {
		$args = [];
		Projects_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}