<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Projects.php');
	include_once(__DIR__ . '/Projects_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Projects');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Projects';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Projects`.`id`" => "id",
		"`Projects`.`Projects_name`" => "Projects_name",
		"`Projects`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`Categories1`.`Category_name`), CONCAT_WS('',   `Categories1`.`Category_name`), '') /* Category */" => "Category",
		"`Projects`.`ProjectTags`" => "ProjectTags",
		"`Projects`.`Image_1`" => "Image_1",
		"`Projects`.`Image_Uploaded`" => "Image_Uploaded",
		"`Projects`.`Geo_place`" => "Geo_place",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Projects`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Categories1`.`Category_name`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => '`Projects`.`Geo_place`',
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Projects`.`id`" => "id",
		"`Projects`.`Projects_name`" => "Projects_name",
		"`Projects`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`Categories1`.`Category_name`), CONCAT_WS('',   `Categories1`.`Category_name`), '') /* Category */" => "Category",
		"`Projects`.`ProjectTags`" => "ProjectTags",
		"`Projects`.`Image_1`" => "Image_1",
		"`Projects`.`Image_Uploaded`" => "Image_Uploaded",
		"`Projects`.`Geo_place`" => "Geo_place",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Projects`.`id`" => "ID",
		"`Projects`.`Projects_name`" => "Project\'s name",
		"`Projects`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`Categories1`.`Category_name`), CONCAT_WS('',   `Categories1`.`Category_name`), '') /* Category */" => "Category",
		"`Projects`.`ProjectTags`" => "ProjectTags",
		"`Projects`.`Image_Uploaded`" => "Image Uploaded",
		"`Projects`.`Geo_place`" => "Google place",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Projects`.`id`" => "id",
		"`Projects`.`Projects_name`" => "Projects_name",
		"`Projects`.`Description`" => "Description",
		"IF(    CHAR_LENGTH(`Categories1`.`Category_name`), CONCAT_WS('',   `Categories1`.`Category_name`), '') /* Category */" => "Category",
		"`Projects`.`ProjectTags`" => "ProjectTags",
		"`Projects`.`Image_Uploaded`" => "Image_Uploaded",
		"`Projects`.`Geo_place`" => "Geo_place",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['Category' => 'Category', ];

	$x->QueryFrom = "`Projects` LEFT JOIN `Categories` as Categories1 ON `Categories1`.`id`=`Projects`.`Category` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Projects_view.php';
	$x->TableTitle = 'Projects';
	$x->TableIcon = 'resources/table_icons/house.png';
	$x->PrimaryKey = '`Projects`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Project\'s name', 'Description', 'Category', 'ProjectTags', 'Image 1', 'Image Uploaded', 'Google place', ];
	$x->ColFieldName = ['Projects_name', 'Description', 'Category', 'ProjectTags', 'Image_1', 'Image_Uploaded', 'Geo_place', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Projects_templateTV.html';
	$x->SelectedTemplate = 'templates/Projects_templateTVS.html';
	$x->TemplateDV = 'templates/Projects_templateDV.html';
	$x->TemplateDVP = 'templates/Projects_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Projects_init
	$render = true;
	if(function_exists('Projects_init')) {
		$args = [];
		$render = Projects_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Projects_header
	$headerCode = '';
	if(function_exists('Projects_header')) {
		$args = [];
		$headerCode = Projects_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Projects_footer
	$footerCode = '';
	if(function_exists('Projects_footer')) {
		$args = [];
		$footerCode = Projects_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
